name: Reusable workflow

on:
  workflow_call:
env:
  NAME: raj
  
jobs:
  
   sample-job1:
    runs-on: ubuntu-latest
    steps:
       -uses: actions/checkout@v3
       -name: write something to log
        run: echo "$NAME"
