name: Reusable workflow

on:
  workflow_call:
  
jobs:
  
  rul-job1:
    runs-on: ubuntu-latest
    steps: 
     -uses: action/checkout@v3
     -name: write something to log
      run : |
        echo " Iam resuable work flow one"
